import React, { createContext, useState } from 'react';

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const translations = {
    en: {
      dashboard: "Dashboard",
      my_patients: "My Patients",
      all_patients: "Patients",
      ai_reports: "AI Reports",
      alerts: "Alerts",
      start_test: "Start Today's Test →",
      welcome_back: "Welcome back",
      sign_in: "Sign In",
      register: "Register",
      reports: "Reports",
      eye_tracking: "Eye Tracking",
      cognibot: "CogniBot",
      notifications: "Notifications",
      take_tests: "Take Tests",
      latest_score: "Latest Score",
      tests_completed: "Tests Completed",
      avg_response_time: "Avg Response Time",
      risk_level: "Risk Level",
      seven_day_progress: "7-Day Progress",
      todays_test: "Today's Test",
      test_history: "Test History",
      day: "DAY",
      date: "DATE",
      score: "SCORE",
      response_time: "RESPONSE TIME",
      attention: "ATTENTION",
      risk: "RISK",
      send_reminder: "Send Reminder",
      view_report: "View Report",
      today: "Today",
      yesterday: "Yesterday",
      urgent_alerts: "Urgent Alerts",
      score_overview: "Score Overview",
      recent_alerts: "Recent Alerts",
      patient: "Patient",
      admin: "Administrator",
      caregiver: "Caregiver",
      system_overview: "System overview",
      patient_management: "Patient management",
      total_patients: "Total Patients",
      active_caregivers: "Active Caregivers",
      high_risk_patients: "High Risk Patients",
      test_completion: "Test Completion",
      patient_list: "Patient List",
      risk_distribution: "Risk Distribution",
      add_patient: "+ Add Patient",
      action: "ACTION",
      memory_recall: "Memory Recall",
      reaction_time: "Reaction Time",
      cognitive_qa: "Cognitive Q&A",
      speech_recall: "Speech Recall",
      diagnostic_notice: "Diagnostic Notice",
      high_risk_detected: "High Risk Detected",
      assessment_completed: "Assessment Completed!",
      submit_results: "Submit & Finalize Results",
      back_to_dashboard: "Back to Dashboard",
      overall_diagnosis: "Weekly Diagnosis"
    },
    ta: {
      dashboard: "முகப்பு",
      my_patients: "என் நோயாளிகள்",
      all_patients: "நோயாளிகள்",
      ai_reports: "AI அறிக்கைகள்",
      alerts: "விழிப்பூட்டல்கள்",
      start_test: "பரிசோதனையைத் தொடங்கு →",
      welcome_back: "மீண்டும் வருக",
      sign_in: "உள்நுழைய",
      register: "பதிவு செய்க",
      reports: "அறிக்கைகள்",
      eye_tracking: "கண் கண்காணிப்பு",
      cognibot: "காக்னிபாட்",
      notifications: "அறிவிப்புகள்",
      take_tests: "சோதனை மேற்கொள்ளவும்",
      latest_score: "சமீபத்திய மதிப்பெண்",
      tests_completed: "முடிக்கப்பட்டவை",
      avg_response_time: "சராசரி பதில் நேரம்",
      risk_level: "ஆபத்து நிலை",
      seven_day_progress: "7 நாள் முன்னேற்றம்",
      todays_test: "இன்றைய சோதனை",
      test_history: "சோதனை வரலாறு",
      day: "நாள்",
      date: "தேதி",
      score: "மதிப்பெண்",
      response_time: "பதில் நேரம்",
      attention: "கவனம்",
      risk: "ஆபத்து",
      send_reminder: "நினைவூட்டல் அனுப்பு",
      view_report: "அறிக்கை காண்",
      today: "இன்று",
      yesterday: "நேற்று",
      urgent_alerts: "அவசர",
      score_overview: "மதிப்பெண் மேலோட்டம்",
      recent_alerts: "சமீபத்திய விழிப்பூட்டல்கள்",
      patient: "நோயாளி",
      admin: "நிர்வாகி",
      caregiver: "பாதுகாவலர்",
      system_overview: "அமைப்பு மேலோட்டம்",
      patient_management: "நோயாளி மேலாண்மை",
      total_patients: "மொத்த நோயாளிகள்",
      active_caregivers: "பாதுகாவலர்கள்",
      high_risk_patients: "அதிக ஆபத்து",
      test_completion: "முடிந்தவை",
      patient_list: "நோயாளி பட்டியல்",
      risk_distribution: "ஆபத்து விநியோகம்",
      add_patient: "+ நோயாளி சேர்",
      action: "செயல்",
      memory_recall: "நினைவாற்றல்",
      reaction_time: "எதிர்வினை நேரம்",
      cognitive_qa: "அறிவாற்றல் வினாடி வினா",
      speech_recall: "பேச்சு நினைவு",
      diagnostic_notice: "நோய் கண்டறிதல் அறிவிப்பு",
      high_risk_detected: "அதிக ஆபத்து கண்டறியப்பட்டது",
      assessment_completed: "மதிப்பீடு முடிந்தது!",
      submit_results: "முடிவுகளை சமர்ப்பிக்கவும்",
      back_to_dashboard: "முகப்பிற்குச் செல்லவும்",
      overall_diagnosis: "வாராந்திர நோய் கண்டறிதல்"
    },
    hi: {
      dashboard: "डैशबोर्ड",
      my_patients: "मेरे मरीज़",
      all_patients: "मरीज़",
      ai_reports: "AI रिपोर्ट",
      alerts: "अलर्ट",
      start_test: "आज का परीक्षण शुरू करें →",
      welcome_back: "वापसी पर स्वागत है",
      sign_in: "साइन इन करें",
      register: "रजिस्टर करें",
      reports: "रिपोर्ट",
      eye_tracking: "नेत्र ट्रैकिंग",
      cognibot: "कॉग्निबॉट",
      notifications: "सूचनाएं",
      take_tests: "परीक्षण करें",
      latest_score: "नवीनतम स्कोर",
      tests_completed: "पूर्ण परीक्षण",
      avg_response_time: "औसत प्रतिक्रिया समय",
      risk_level: "जोखिम स्तर",
      seven_day_progress: "7-दिन की प्रगति",
      todays_test: "आज का परीक्षण",
      test_history: "परीक्षण इतिहास",
      day: "दिन",
      date: "तारीख",
      score: "स्कोर",
      response_time: "जवाब का समय",
      attention: "ध्यान",
      risk: "जोखिम",
      send_reminder: "रिमाइंडर भेजें",
      view_report: "रिपोर्ट देखें",
      today: "आज",
      yesterday: "कल",
      urgent_alerts: "तत्काल अलर्ट",
      score_overview: "स्कोर ओवरव्यू",
      recent_alerts: "हाल के अलर्ट",
      patient: "मरीज़",
      admin: "प्रशासक",
      caregiver: "देखभाल करने वाला",
      system_overview: "सिस्टम ओवरव्यू",
      patient_management: "रोगी प्रबंधन",
      total_patients: "कुल मरीज़",
      active_caregivers: "सक्रिय देखभालकर्ता",
      high_risk_patients: "उच्च जोखिम वाले मरीज़",
      test_completion: "परीक्षण पूर्णता",
      patient_list: "मरीज़ सूची",
      risk_distribution: "जोखिम वितरण",
      add_patient: "+ मरीज़ जोड़ें",
      action: "कार्रवाई",
      memory_recall: "याददाश्त",
      reaction_time: "प्रतिक्रिया समय",
      cognitive_qa: "संज्ञानात्मक प्रश्नोत्तरी",
      speech_recall: "भाषण स्मरण",
      diagnostic_notice: "नैदानिक सूचना",
      high_risk_detected: "उच्च जोखिम का पता चला",
      assessment_completed: "मूल्यांकन पूर्ण!",
      submit_results: "परिणाम जमा करें",
      back_to_dashboard: "डैशबोर्ड पर वापस जाएं",
      overall_diagnosis: "साप्ताहिक निदान"
    }
  };

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
